apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 500m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.nais.preprod.local
    - https://familie-ef-mottak.dev-fss-pub.nais.io
    - https://familie-ef-mottak.dev-fss.nais.io
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  leaderElection: true
