server:
  port: 8092
  servlet:
    context-path: /
spring:
  datasource:
    username: postgres
    password: test
    url: jdbc:postgresql://0.0.0.0:5432/familie-ef-mottak

logging:
  config: "classpath:logback-test.xml"
