no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      acceptedaudience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      proxyurl: http://webproxy-nais.nav.no:8088
      cookie_name: selvbetjening-idtoken
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    azuread:
      discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
      accepted_audience: ${CLIENT_ID}
      proxyurl: http://webproxy-nais.nav.no:8088
      cookie_name: azure_token
  client:
    registration:
      integrasjoner-client-credentials:
        resource-url: ${familie.ef.integrasjoner.url}
        token-endpoint-url: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      infotrygd-replika:
        resource-url: ${INFOTRYGD_REPLIKA_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${EF_INFOTRYGD_REPLIKA_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ef-sak:
        resource-url: ${EF_SAK_URL}
        token-endpoint-url: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.teamfamilie.familie-ef-sak/.default
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      dokument:
        resource-url: ${familie.dokument.url}
        well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        token-exchange:
          audience: ${familie.dokument.audience}
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-auth-method: private_key_jwt
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
