spring:
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd:
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    properties:
      schema.registry.url: https://kafka-schema-registry.nais-q.adeo.no/
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ef-mottak
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1

familie:
  dokument:
    url: http://familie-dokument
    audience: dev-gcp:teamfamilie:familie-dokument
  ef:
    pdfgenerator:
      url: http://familie-brev
    integrasjoner:
      url: https://familie-integrasjoner.dev-fss-pub.nais.io/api

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      cookie_name: azure_token
  client:
    registration:
      integrasjoner-client-credentials:
        resource-url: ${familie.ef.integrasjoner.url}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      infotrygd-replika:
        resource-url: ${INFOTRYGD_REPLIKA_API_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${EF_INFOTRYGD_REPLIKA_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ef-sak:
        resource-url: ${EF_SAK_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://dev-gcp.teamfamilie.familie-ef-sak/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      dokument:
        resource-url: ${familie.dokument.url}
        well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        token-exchange:
          audience: ${familie.dokument.audience}
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-auth-method: private_key_jwt
          client-jwk: ${TOKEN_X_PRIVATE_JWK}

INFOTRYGD_REPLIKA_API_URL: https://infotrygd-enslig-forsoerger.dev-fss-pub.nais.io

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-q2
dittnav.soknadfrontendUrl: https://www-q0.nav.no/familie/alene-med-barn/soknad
dittnav.ettersendingUrl: https://ensligmorellerfar.dev.nav.no/familie/alene-med-barn/ettersending

KAFKA_ONPREM_BOOTSTRAP_SERVERS: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
KAFKA_ONPREM_SCHEMA_REGISTRY_URL: https://kafka-schema-registry.nais-q.adeo.no/

EF_SAK_URL: http://familie-ef-sak
ettersending.ettersendingUrl: https://ensligmorellerfar.dev.nav.no/familie/alene-med-barn/ettersending