server:
  servlet:
    context-path: /


familie:
  ef:
    sak:
      url: https://api-gw.oera.no/familie-ef-sak/api/
    arkiv:
        url:
spring:
  data:
    jdbc:
      repositories:
        enabled: true
#  flyway:
#    schemas: "familie-ef-mottak"
#    enabled: true

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true