application:
  name: "familie-ef-mottak"
server:
  servlet:
    context-path: /

spring:
  data:
    jdbc:
      repositories:
        enabled: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  kafka:
    client-id: familie-ef-mottak
    bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    properties:
      schema.registry.url: http://kafka-schema-registry.tpa:8081
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SRV_CREDENTIAL_USERNAME}" password="${SRV_CREDENTIAL_PASSWORD}";
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: srvfamilie-ef-mot
      max-poll-records: 1
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  flyway:
    enabled: true
    baseline-version: 6
    ignore-missing-migrations: true
  datasource:
    url: jdbc:postgresql://A01DBVL010.adeo.no:5432/familie-ef-mottak
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
logging:
  config: "classpath:logback-spring.xml"

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      health: "status/isAlive"
  metrics.export.prometheus.enabled: true
  health:
    db:
      enabled: true

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    environment: ${NAIS_CLUSTER_NAME}
    applicationName: ${NAIS_APP_NAME}

familie:
  dokument:
    url: https://familie-dokument.intern.nav.no
    audience: prod-gcp:teamfamilie:familie-dokument
  ef:
    integrasjoner:
      url: http://familie-integrasjoner.teamfamilie/api/
    pdfgenerator:
      url: https://familie-ef-dokgen.intern.nav.no/

prosessering:
  cronRetryTasks: "0 5 6,7 1/1 * ?"
  fixedDelayString:
    in:
      milliseconds: 10000
  delete:
    after:
      weeks: 4

database:
  encryption:
    # 16, 24 or 32 bytes
    key: ${DATABASEKEY}

INFOTRYGD_REPLIKA_API_URL: https://infotrygd-enslig-forsoerger.nais.adeo.no
EF_SAK_URL: https://familie-ef-sak.intern.nav.no

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-p
KAFKA_TOPIC_DITTNAV: aapen-brukernotifikasjon-nyBeskjed-v1
#STS_URL: http://security-token-service.default.svc.nais.local
dittnav.soknadfrontendUrl: https://www.nav.no/familie/alene-med-barn/soknad
ettersending.ettersendingUrl: https://www.nav.no/familie/alene-med-barn/ettersending