server:
  port: 8092
  servlet:
    context-path: /

spring:
  datasource:
    username: postgres
    password: test
    url: jdbc:postgresql://localhost:5432/familie-ef-mottak
  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: srvc01

familie:
  ef:
    integrasjoner:
      url: http://localhost:8092/mockintegrasjoner/
    pdfgenerator:
      #url: http://localhost:8081/
      url: https://familie-ef-dokgen.dev.intern.nav.no/

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://localhost:4242/api
    environment: local
    applicationName: familie-ef-mottak

logging:
  config: "classpath:logback-test.xml"

no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
      cookie_name: localhost-idtoken
      proxyurl:
  client:
    registration:
      integrasjoner-client-credentials:
        resource-url: ${familie.ef.integrasjoner.url}
        token-endpoint-url: http://localhost:8092/mockapi/token
        grant-type: client_credentials
        scope: anything4
        authentication:
          client-id: anything5
          client-secret: anything6
          client-auth-method: client_secret_basic


database:
  encryption:
    # 16, 24 or 32 bytes
    key: Det finnes mange gode eksempler.

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-q1
SRV_CREDENTIAL_USERNAME: test
SRV_CREDENTIAL_PASSWORD: test

dittnav.soknadfrontendUrl: http://localhost:3000/familie/alene-med-barn/soknad
