application:
  name: "familie-ef-mottak"
server:
  servlet:
    context-path: /

spring:
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    baseline-version: 6
    ignore-missing-migrations: true
  datasource:
    url: jdbc:postgresql://A01DBVL010.adeo.no:5432/familie-ef-mottak
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
logging:
  config: "classpath:logback-spring.xml"

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      health: "status/isAlive"
  metrics.export.prometheus.enabled: true
  health:
    db:
      enabled: true


familie:
  ef:
    sak:
      url: http://familie-ef-sak/api/
    integrasjoner:
      url: http://familie-integrasjoner/api/
    pdfgenerator:
      url: https://familie-ef-dokgen.nais.adeo.no/

no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
      acceptedaudience: ${ACCEPTEDAUDIENCE}
      proxyurl: http://webproxy-nais.nav.no:8088
      cookie_name: selvbetjening-idtoken
    azuread:
      discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
      accepted_audience: ${CLIENT_ID}
      proxyurl: http://webproxy-nais.nav.no:8088
      cookie_name: azure_token
  client:
    registration:
      ef-sak-client-credentials:
        resource-url: ${familie.ef.sak.url}
        token-endpoint-url: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${EF_SAK_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic
      integrasjoner-client-credentials:
        resource-url: ${familie.ef.integrasjoner.url}
        token-endpoint-url: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

database:
  encryption:
    # 16, 24 or 32 bytes
    key: ${DATABASEKEY}



#STS_URL: http://security-token-service.default.svc.nais.local
